### ISSUE TITLE
Primitive numbers (e.g. `nat`)

### ISSUE THREAD

**Issue by anton-trunov** [anton-trunov/modal-type-theory#27]
We will need constructors and an eliminator + a bunch of primitive operations (addition, multiplication, etc.). One option is to use arbitrary-precision arithmetic for `nat`, e.g. the [Zarith](https://github.com/ocaml/Zarith) library.

Keywords:
[PCF](https://en.wikipedia.org/wiki/Programming_Computable_Functions),
[System T](https://en.wikipedia.org/wiki/Dialectica_interpretation)

**Comment by sloboegen** [comment]
Implementing this issue

**Comment by anton-trunov** [comment]
Implemented in #41
