### ISSUE TITLE
Improve error reporting for capturing regular vars in modal contexts

### ISSUE THREAD

**Issue by anton-trunov** [anton-trunov/modal-type-theory#38]
Right now one gets
```
$ mtt infer -e "λf:B -> []A. λy:B. (λx:[]A. box x) (f y)"
Type inference error: Variable x is not found in the regular context
```
which is not particularly helpful and might be even misleading.

**Comment by GoPavel** [comment]
If I understand right misleading appears due to ambiguity of contexts.

I guess the perfect solution is tracking both contexts and when an error happens we collect traceback of changing contexts and pretty print it to give enough information about the problem.
For example: 
```
$ mtt infer -e "λf:B -> []A. λy:B. (λx:[]A. box x) (f y)"
Type inference error: Variable x is not found regular context. 
Traceback: 
from "x" in contexts Γ = {}, D = {}
from "box x" in contexts Γ = {f: B -> □ A, y: B, x: □A}, D = {}
from "λx:[]A. box x" in context {f: B -> □ A, y: B}, D = {}
...
```
But it will blow up memory for large terms. Maybe some threshold for traceback's size is needed.

In the above example, printing only the current context wouldn't clarify anything.  
But the second line is helpful for find overlook.

**Comment by GoPavel** [comment]
By the way, right now the message is different: 
```
$ mtt infer -e "λf:B -> []A. λy:B. (λx:[]A. box x) (f y)"
mtt: Type inference error: x is not found in the environment!
     file name :  Not a file, lines :  0 - 0, column :  32 - 33
```
Location is added and after deduplication in `Env.ml` environment is not clarified.

**Comment by anton-trunov** [comment]
If we talk in terms of concrete implementation then I was thinking we could add a dummy element into the regular context once we get inside a `box`. Then the environment lookup would try to find a regular variable until it hits a dummy var, it will continue the search further down the env and will report different kinds of errors if it finds a variable (which might mean non-legit usage, or a typo) or if there is no var at all (which probably means a typo).

**Comment by GoPavel** [comment]
Firstly, I tried to understand what behavior we want.
What kind of errors we want to clarify:
1) mixing up modal and regular contexts: 
`λx:[]A. box x` -- `x` in modal, but not in the regular context. 

But now I noticed that the modal variables have their own token which makes it impossible :)

2) Variable not found and it occurs in the staged expression (from the `box`):
`λx: A. ... box (.. f x ..) ` -- the introduction of regular variable `x: A` is not reached from the `box`.

For the second case, I tried to give a comprehensive message that clarifies what causes the error.
Maybe it's over-engineering and looks like finding a proof derivation tree. 

As I understand you suggest marking situations when we are inferring types in the `box` by dummy element and toss message which like  `regular variable "x" is not found in the staged expression`. 
Also we can save the location of the nearest `box`  in AST into the dummy for clarification.

**Comment by anton-trunov** [comment]
> Also we can save the location of the nearest box in AST into the dummy for clarification.

Actually, I'd rather
1. add location information to bound variables,
2. introduce `error` type so that it can be pattern-matched on to see the reason of a failure
3. process failures arising from typechecking `box`-expressions instead of propagating them as they are

and report something like
> regular variable "x" (bound at \<line:column\>) cannot be accessed inside boxed expression \<range\>

for the example you mentioned.

The` error` type would be a polymorphic variant type (see [this](https://keleshev.com/composable-error-handling-in-ocaml) blog post) like so:
```
type error =
  | `EnvUnboundRegularVar of ...  (* additional info in case we need more context *)
  | `EnvRegularVarOutsideBox of ...
  | ...
```

**Comment by GoPavel** [comment]
I added following examples: 
``` bash
modal-type-theory on  improve_error_reporting [!?] 
➜ cat examples/unknown_variable_in_box{1,2,3,4}.mtt
λx:A. box (λy:B. box (λz:[]A. z))
λx:A. box (λy:B. box (λz:[]A. y))
λx:A. box (λy:B. box (λz:[]A. x))
λx:A. box (λy:B. box (λz:[]A. w))

modal-type-theory on  improve_error_reporting [!?] 
➜ dune exec -- mtt infer examples/unknown_variable_in_box1.mtt
A → □(B → □(□A → □A))

modal-type-theory on  improve_error_reporting [!?] 
➜ dune exec -- mtt infer examples/unknown_variable_in_box2.mtt
mtt: Type inference error: regular variable y (bound at 30:31) cannot accessed from boxed expression
     file name :  Not a file, lines :  1 - 1, column :  17 - 32

modal-type-theory on  improve_error_reporting [!?] 
➜ dune exec -- mtt infer examples/unknown_variable_in_box3.mtt
mtt: Type inference error: regular variable x (bound at 30:31) cannot accessed from boxed expression
     file name :  Not a file, lines :  1 - 1, column :  6 - 33

modal-type-theory on  improve_error_reporting [!?] 
➜ dune exec -- mtt infer examples/unknown_variable_in_box4.mtt
mtt: Type inference error: w is not found in the regular environment!
     file name :  Not a file, lines :  1 - 1, column :  30 - 31
```
