### ISSUE TITLE
Automatic update `ParserErrors.messages` file after changes in grammar

### ISSUE THREAD

**Issue by sloboegen** [anton-trunov/modal-type-theory#40]
Here is the issue: `menhir --update-errors` is highly unstable, sometimes it can update the `.messages` file, sometimes it cannot.

A proposed workaround here:
1. Cover each and every error state in cram tests.
1. After a change in the grammar, regenerate `.messages` file from scratch (`menhir --list-errors src/Parser.mly > src/ParserErrors.messages`).
1. Create a dedicated Dune *build profile* (let's call it `parser-errors`) which would add parser *state numbers* to the parser errors, this can be done e.g. like so
   ```
   let handle_syntax_error _lexbuf checkpoint =
   let message =
     let state_id = state checkpoint in
     match ParserErrors.message state_id with
     | exception Caml.Not_found ->
         "Unrecognized syntax error. Please report your example"
     | msg -> [%string "[state #$(Int.to_string state_id)]: $msg"]. (* !!! *)
   in
   Result.fail @@ String.strip message
   ```
   But the part marked with `!!!` needs to be compiled conditionally (for instance, it should be off for release/debug compilation).
0. Use `dune runtest --profile parser-errors`'s output to generate the diff with state numbers which can be used to automatically update `.messages` file with a script (this needs to be written).

**Comment by anton-trunov** [comment]
Fixed with #41, more or less :)
